[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/netlify-functions" # Directory dove sono generate le Funzioni

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # Nome della Funzione SSR
  status = 200
